# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FrientInforView.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(381, 517)
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(70, 180, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(70, 420, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(70, 340, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(70, 267, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(70, 227, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(70, 300, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(70, 380, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.id_number = QtWidgets.QLabel(Form)
        self.id_number.setGeometry(QtCore.QRect(220, 180, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.id_number.setFont(font)
        self.id_number.setObjectName("id_number")
        self.nc_name = QtWidgets.QLabel(Form)
        self.nc_name.setGeometry(QtCore.QRect(220, 220, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.nc_name.setFont(font)
        self.nc_name.setObjectName("nc_name")
        self.signture = QtWidgets.QLabel(Form)
        self.signture.setGeometry(QtCore.QRect(220, 270, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.signture.setFont(font)
        self.signture.setObjectName("signture")
        self.gender = QtWidgets.QLabel(Form)
        self.gender.setGeometry(QtCore.QRect(220, 300, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.gender.setFont(font)
        self.gender.setObjectName("gender")
        self.birthday = QtWidgets.QLabel(Form)
        self.birthday.setGeometry(QtCore.QRect(220, 340, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.birthday.setFont(font)
        self.birthday.setObjectName("birthday")
        self.phone_num = QtWidgets.QLabel(Form)
        self.phone_num.setGeometry(QtCore.QRect(220, 380, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.phone_num.setFont(font)
        self.phone_num.setObjectName("phone_num")
        self.email = QtWidgets.QLabel(Form)
        self.email.setGeometry(QtCore.QRect(220, 420, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.email.setFont(font)
        self.email.setObjectName("email")
        self.photo = QtWidgets.QLabel(Form)
        self.photo.setGeometry(QtCore.QRect(140, 40, 121, 91))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.photo.setFont(font)
        self.photo.setObjectName("photo")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_10.setText(_translate("Form", "账号："))
        self.label_5.setText(_translate("Form", "输入邮箱号码："))
        self.label_9.setText(_translate("Form", "出生日期："))
        self.label_4.setText(_translate("Form", "个性签名："))
        self.label_3.setText(_translate("Form", "昵称："))
        self.label_6.setText(_translate("Form", "选择性别："))
        self.label.setText(_translate("Form", "输入手机号码："))
        self.id_number.setText(_translate("Form", "00000"))
        self.nc_name.setText(_translate("Form", "00000"))
        self.signture.setText(_translate("Form", "00000"))
        self.gender.setText(_translate("Form", "00000"))
        self.birthday.setText(_translate("Form", "00000"))
        self.phone_num.setText(_translate("Form", "00000"))
        self.email.setText(_translate("Form", "00000"))
        self.photo.setText(_translate("Form", "touxiang"))
